---
# Performance Framework for Hites
version: '3.2'
services:
  master:
    image: "joabgonzalez/jmtm:hites"
    stdin_open: true
    tty: true
    volumes:
      - "jmeter-results:/jmeter/apache-jmeter/bin/results"
      - "jmeter-tests:/jmeter/apache-jmeter/bin/tests"
    networks:
      - "performance"
    deploy:
      placement:
        constraints:
          - "node.role == worker"
      resources:
        limits:
          cpus: '2'
          memory: 5120M
        reservations:
          cpus: '2'
          memory: 5120M
  slave:
    image: "joabgonzalez/jmts:hites"
    depends_on:
      - "master"
    stdin_open: true
    tty: true
    volumes:
      - "jmeter-data:/jmeter/apache-jmeter/bin/data"
    networks:
      - "performance"
    deploy:
      placement:
        constraints:
          - "node.role == worker"
      resources:
        limits:
          cpus: '1'
          memory: 5120M
        reservations:
          cpus: '1'
          memory: 5120M
  redis:
    image: "redis"
    hostname: "redis"
    ports:
      - "6379:6379"
    networks:
      - "performance"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
  influxdb:
    image: "influxdb"
    hostname: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=performance"
      - "INFLUXDB_USER=performance"
      - "INFLUXDB_USER_PASSWORD=performance123"
    volumes:
      - "jmeter-influxdb:/var/lib/influxdb"
    networks:
      - "performance"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
  grafana:
    image: "grafana/grafana"
    ports:
      - "80:3000"
    volumes:
      - "jmeter-grafana:/var/lib/grafana"
    networks:
      - "performance"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
networks:
  performance:
    driver: overlay
    attachable: true
volumes:
  jmeter-results:
    external: true
  jmeter-tests:
    external: true
  jmeter-data:
    external: true
  jmeter-influxdb:
    external: true
  jmeter-grafana:
    external: true
