#Base de Jmater Tsoft
FROM tsoft/jmeter-base

#Metadatos
LABEL author="joabgonzalez" jmeter="master"

#Puertos
EXPOSE 60000

#Directorios
VOLUME ${JMETER_HOME}/bin/tests
VOLUME ${JMETER_HOME}/bin/results